name: ZingMusic
version: 1.0.0
slug: zingmusic
description: A custom streaming music assistant focused entirely on ZingMusic.app – browse, search, and play albums and tracks directly from Zing.
url: https://zingmusic.app
arch:
  - amd64
  - aarch64
homeassistant_api: true
auth_api: true
host_network: true
ingress: true
ingress_port: 8095
panel_icon: mdi:music
panel_title: ZingMusic
panel_admin: false
uart: false
map:
  - media:rw
init: false
advanced: false
backup_exclude:
  - cache.db
  - collage_images/*
  - .cache/*
stage: stable
image: ghcr.io/YOUR_GITHUB_USERNAME/zingmusic
tmpfs: true
options:
  log_level: info
  safe_mode: false
schema:
  log_level: list(debug|info|warning|error)
  safe_mode: bool
privileged:
  - SYS_ADMIN
  - DAC_READ_SEARCH
