name: ZingMusic
version: "1.0.0"
slug: zingmusic
description: Custom Music Assistant server with ZingMusic provider
url: https://github.com/Shwerzb/zingmusic-home-assistant-addon
arch:
  - amd64
  - aarch64
startup: services
homeassistant_api: true
host_network: true
ingress: true
ingress_port: 8095
panel_icon: mdi:music
panel_title: ZingMusic
map:
  - media:rw
init: false
tmpfs: true
options:
  log_level: info
schema:
  log_level: list(debug|info|warning|error)